# Dev 환경 설정 (MySQL 8.4.x 사용)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: false


# 개발 서버 로깅 설정
logging:
  level:
    com.attune-me: DEBUG
    org.springframework.web: DEBUG




# API 서버 URL 설정
api:
  server:
    url: http://api.attune-me.com:8080
    description: Develop Server
