spring:
  application:
    name: attune

  profiles:
    default: local

  # application-secret.yml import
  config:
    import:
      - optional:classpath:application-secret.yml

  jpa:
    open-in-view: false # OSIV 비활성화 (성능/안정성 향상)

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


# Springdoc OpenAPI (Swagger)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json



# Spring Boot Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  metrics:
    export:
      simple:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: never
      show-components: never
  health:
    db:
      enabled: false
    diskspace:
      enabled: false



# 앱 공통 설정
app:
  frontend-url: http://localhost:3000

# Logging 설정
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
