# ⚠️ 이 파일은 .gitignore에 포함되어 Git에 커밋되지 않습니다
# ⚠️ 실제 환경에서는 아래 값들을 실제 정보로 변경해야 합니다
# ⚠️ 팀 노션 페이지에서 실제 값을 확인하세요

---
# 공통 설정 (모든 프로파일)
spring:
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static:
      s3:
        bucket:
      ses:
        from-email:


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: openid,profile,email
            redirect-uri: "${oauth2.base-url}/oauth/redirect/google"
          kakao:
            client-id:
            client-secret:
            scope: profile_nickname,account_email
            authorization-grant-type: authorization_code
            redirect-uri: "${oauth2.base-url}/oauth/redirect/kakao"
        provider:
          kakao:
            authorization-uri:
            token-uri:
            user-info-uri:
            user-name-attribute: id
  schedule:
    pool-size: 10



jwt:
  secret-key:
  access-token-expiration:
  refresh-token-expiration:
---


# Dev 환경용 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url:
    username:
    password:
  data:
    redis:
      host:
      port:
  mail:
    username:
    password:

oauth2:
  base-url:



---
# Prod 환경용 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
  data:
    redis:
      host:
      port:
  mail:
    username:
    password:

oauth2:
  base-url: