name: Load Test Observe

on:
  workflow_dispatch:

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ${{ secrets.DEV_EC2_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script_stop: true
          script: |
            curl --silent http://127.0.0.1:8081/actuator/metrics/hikaricp.connections.active
            curl --silent http://127.0.0.1:8081/actuator/metrics/hikaricp.connections.pending
            curl --silent http://127.0.0.1:8081/actuator/metrics/jvm.memory.used
            docker stats --no-stream attune-dev-apps
